### ISSUE TITLE
дублювання коду

### ISSUE THREAD

**Issue by pecourses** [mishakravchenia/pe2024-project.html#7]
https://github.com/mishakravchenia/pe2024-project.html/blob/cbe41ce7f464285fe4b9dae7bc119a4c93742256/assets/css/styles.css#L64-L93
- в трьох секціях однакові правила окрім як для тла, тому, щоб не писати одне й те саме 3 рази і не довелося при підтримці коду, якщо щось треба змінити в картках, редагувати одразу в трьох місцях, то винести повторювані властивості в єдине джерело істини, а окремі залишити:
```css
.sub-head-c,
.sub-head-d,
.sub-head-e {
  border: 1.5px rgb(39, 39, 38) solid;
  border-radius: 15px;
  display: inline-block;
  margin: 10px;
  padding: 1em;
  width: 15em;
}
.sub-head-c {
  color: white;
  background-color: rgba(229, 174, 119, 0.749);
}
.sub-head-d {
  color: #86592d;
  background-color: rgba(255, 241, 223, 0.858);
}
.sub-head-e {
  color: white;
  background-color: #63b4c8d0;
}
``` 
- аналогічне буде плюсом зробити для .main-foto-1, 2, 3
